# Name of the action visible in the action overview
name: Transform tokens send from figma
on:
  push:
    branches:
      - develop
    paths:
      - 'tokens/design-tokens.json'
jobs:
  build:
    name: Transform Figma design tokens for specific platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Transform design tokens
        run: 'yarn install --pure-lock i && yarn transform-tokens'
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Tokens updated'
          title: 'Design tokens updated'
          body: 'Design tokens have been updated via Figma and need to be reviewed.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
