# Name of the action visible in the action overview
name: Transform tokens send from figma
on:
  push:
    branches:
      - design-tokens
    paths:
      - 'tokens/design-tokens.json'
jobs:
  build:
    name: Transform Figma design tokens for specific platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Transform design tokens
        run: 'yarn install --pure-lock && node transformTokens.js'
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Tokens updated'
          title: 'Design tokens updated'
          body: 'Design tokens have been updated via Figma and need to be reviewed.'
          delete-branch: true
          branch: design-tokens
          base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
